### PR TITLE
Fix #13 and OOP-related improvements

### LINKED ISSUE #13: Wrong calculation for recipes that produce multiple items
A few examples:

sfcalc_copper_wire

sfcalc_cloth

sfcalc_rune

### PR DESCRIPTION
**Pull request by char3210**
instead of creating a new Calculator instance every time someone wants to calculate something, just have it be a static class since a Calculator isn't mutable. also kept blacklistedRecipes and blacklistedIds in SFCalc.java since it's only used once so there's no need to store it in the Calculator. the cache is now also implemented in the correct scope(global). finally, the calculation is restructured so that the items you make are stored in a simulated inventory, which fixes #13.

### CODE REVIEW

File: src/main/java/io/github/seggan/sfcalc/Calculator.java [hunk 1]
```diff
@@ -100,66 +105,71 @@ public void printResults(@Nonnull CommandSender sender, @Nonnull SlimefunItem it
...
+        }
 
-            if (calculated.containsKey(i)) { // check already calculated items
-                addAll(result, calculated.get(i), amount);
-                continue;
+        //uncraft submaterials
+        SlimefunItemStack next = getNextItem(result);
+        while(next != null) {
+            int multiplier = next.getItem().getRecipeOutput().getAmount();
+            Long operations = (result.get(next)+multiplier-1)/multiplier; //ceiling(needed/multiplier) but abusing fast ints
```
Comment (Seggan) [inline src/main/java/io/github/seggan/sfcalc/Calculator.java]:
```suggestion
            long operations = (result.get(next)+multiplier-1)/multiplier; //ceiling(needed/multiplier) but abusing fast ints
```
please, dont use wrapped types

File: src/main/java/io/github/seggan/sfcalc/Calculator.java [hunk 2]
```diff
@@ -43,52 +43,57 @@
...
+
+            // This will put our entries in order from lowest to highest
+            List<Map.Entry<ItemStack, Long>> entries = new ArrayList<>(results.entrySet());
+            entries.sort(Comparator.comparingLong(Map.Entry::getValue));
+
+            if (needed && sender instanceof Player) {
+                Map<ItemStack, Long> inv = getInventoryAsItemList((Player) sender);
+
+                for (Map.Entry<ItemStack, Long> entry : entries) {
+                    Long inInventory = inv.getOrDefault(entry.getKey(), 0L);
```
Comment (Seggan) [inline src/main/java/io/github/seggan/sfcalc/Calculator.java]:
```suggestion
                    long inInventory = inv.getOrDefault(entry.getKey(), 0L);
```

File: src/main/java/io/github/seggan/sfcalc/Calculator.java [hunk 3]
```diff
@@ -100,66 +105,71 @@ public void printResults(@Nonnull CommandSender sender, @Nonnull SlimefunItem it
...
         }
 
         return inv;
     }
 
     @Nonnull
-    public Map<ItemStack, Long> calculate(@Nonnull SlimefunItem item) {
-        Map<ItemStack, Long> result = new HashMap<>();
-        Map<ItemStack, Map<ItemStack, Long>> calculated = new HashMap<>(); // stores names that are already calculated for reference
+    public Map<ItemStack, Long> calculate(@Nonnull SlimefunItem parent, Long amount) {
```
Comment (Seggan) [inline src/main/java/io/github/seggan/sfcalc/Calculator.java]:
```suggestion
    public Map<ItemStack, Long> calculate(@Nonnull SlimefunItem parent, long amount) {
```

**Review by Seggan — CHANGES_REQUESTED** [review]
Please, dont use wrapped types. Looks good otherwise

**Review by Seggan — APPROVED** [review]
